// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnSmlwIzqYe2QaoVUk3lKTI8wokWnbGBk',
    appId: '1:707776487238:web:593ad2a1f4aa4544614f47',
    messagingSenderId: '707776487238',
    projectId: 'eemi-8d4ff',
    authDomain: 'eemi-8d4ff.firebaseapp.com',
    storageBucket: 'eemi-8d4ff.firebasestorage.app',
    measurementId: 'G-0G03YGZ9WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1LXZXCCSIyPjV-t_G0r9JKsNrF7fezqk',
    appId: '1:707776487238:android:afdf2ce275df61c2614f47',
    messagingSenderId: '707776487238',
    projectId: 'eemi-8d4ff',
    storageBucket: 'eemi-8d4ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBur0nu54aMd9sOTFfs7uUO0ihpcSN701Q',
    appId: '1:707776487238:ios:eb19ba678393ba82614f47',
    messagingSenderId: '707776487238',
    projectId: 'eemi-8d4ff',
    storageBucket: 'eemi-8d4ff.firebasestorage.app',
    iosBundleId: 'com.eemi.flutter.flutter5Wd',
  );
}
